services:
  - type: web
    name: haxball-js-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HAXBALL_TOKEN
        sync: false  # يجب ضبطه في dashboard يدوياً